config/routes.rb
Rails.application.routes.draw do
  devise_for :usuarios
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :empresas, only: %i[index show] 
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  belongs_to :vendedor
  belongs_to :empresa
end

app/models/empresa.rb
class Empresa < ApplicationRecord
	with_options presence:{message:'não pode ficar em branco'} do
		validates 	:cnpj,
					:razao_social,
					:endereco,
					:email_faturamento
	end
	with_options  uniqueness:{message:'já está em uso'} do
		validates	:cnpj,
					:razao_social,
					:endereco,
					:email_faturamento
	end
end

app/models/pagamento.rb
class Pagamento < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
  belongs_to :pagamento
  belongs_to :empresa
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #validates_format_of :email, with: /\A^[a-zA-Z0-9._-]+@[a-zA-Z0-9]+\.[a-zA-Z\.a-zA-Z]\z/i 
  
  end

app/models/vendedor.rb
class Vendedor < ApplicationRecord
  belongs_to :empresa
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/empresas_controller.rb
class EmpresasController<ApplicationController

	def index
		@empresas=Empresa.all
	end

	def show
		@empresa = Empresa.find(params[:id])
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/empresas/index.html.erb
<% if @empresas.empty? %>
	<p>Nenhuma empresa cadastrada</p>
<% end %>

<% @empresas.each do |empresa| %>
	<h1><%=link_to empresa.razao_social, empresa%></h1>
	<p><%= empresa.cnpj %></p>
	<p><%= empresa.email_faturamento%></p>
<%end%>

<%=link_to 'Voltar', root_path%>

app/views/empresas/show.html.erb
<h1><%= @empresa.razao_social %></h1>
<dl>
	<dt>CNPJ</dt>
	<dd><%=@empresa.cnpj %></dd>
	<dt>Endereço</dt>
	<dd><%=@empresa.endereco%></dd>
	<dt>Email de faturamento</dt>
	<dd><%=@empresa.email_faturamento %></dd>
	<dt>Token</dt>
	<dd><%=@empresa.token%></dd>
</dl>

<%=link_to 'Voltar',empresas_path %>

app/views/home/index.html.erb

<h1>Paynow</h1>

<%=link_to 'Empresas', empresas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paynow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav>
      <% if usuario_signed_in?%>
        <%= current_usuario.email %>
        <%= link_to 'Sair', destroy_usuario_session_path, method: :delete %>
        <a href="<%= root_path %>" class="" data-method="delete">Inicio</a>
      <% else %>
          <%= link_to 'Logar', new_usuario_session_path %>
          <%= link_to 'Criar conta', new_usuario_registration_path %>
      <% end %>
    </nav>
  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>